schema_version: 1

context:
  name: shapiq
  version: "1.5.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/shapiq-${{ version }}.tar.gz
  sha256: 6336d764ce27836b69a1d3283392d69c8c2f4dcd3f52e19d2ad037d5aac1708c
  patches:
    - if: osx
      then:
        - patches/0001-osx-dynamic-openmp.patch

build:
  number: 0
  skip: match(python, "<3.12")
  script: |
    export LIBOMP_PREFIX=$PREFIX
    ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - setuptools >=69
    - setuptools-scm >=8
    - wheel
    - numpy
    - pip
    - if: osx
      then:
        - llvm-openmp
  run:
    - python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - tqdm
    - requests
    - matplotlib-base
    - networkx
    - colour
    - pillow
    - joblib

tests:
  - python:
      imports:
        - shapiq
      pip_check: true

about:
  summary: Shapley Interactions for Machine Learning
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/mmschlk/shapiq

extra:
  recipe-maintainers:
    - janjagusch
