schema_version: 1

context:
  name: shapiq
  version: "1.3.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/shapiq-${{ version }}.tar.gz
  sha256: 4686281edb6fbfe4e3678db09b2dd217f85345c9a265b3b38e81c41da62c218a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - tqdm
    - requests
    - sparse-transform
    - galois
    - matplotlib-base
    - networkx
    - colour
    - pillow
    - overrides

tests:
  - python:
      imports:
        - shapiq
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Shapley Interactions for Machine Learning
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/mmschlk/shapiq

extra:
  recipe-maintainers:
    - janjagusch
